// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// altumage_forward
Rcpp::NumericVector altumage_forward(std::string weights_file, Rcpp::NumericMatrix Xin);
RcppExport SEXP _methylclock_altumage_forward(SEXP weights_fileSEXP, SEXP XinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type weights_file(weights_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xin(XinSEXP);
    rcpp_result_gen = Rcpp::wrap(altumage_forward(weights_file, Xin));
    return rcpp_result_gen;
END_RCPP
}
// bnn_predict
Rcpp::NumericVector bnn_predict(Rcpp::RObject odata);
RcppExport SEXP _methylclock_bnn_predict(SEXP odataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type odata(odataSEXP);
    rcpp_result_gen = Rcpp::wrap(bnn_predict(odata));
    return rcpp_result_gen;
END_RCPP
}
// mc_knn_impute_mem
Rcpp::NumericMatrix mc_knn_impute_mem(Rcpp::NumericMatrix Bin, int k, int maxp, double rowmax, double colmax);
RcppExport SEXP _methylclock_mc_knn_impute_mem(SEXP BinSEXP, SEXP kSEXP, SEXP maxpSEXP, SEXP rowmaxSEXP, SEXP colmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Bin(BinSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type maxp(maxpSEXP);
    Rcpp::traits::input_parameter< double >::type rowmax(rowmaxSEXP);
    Rcpp::traits::input_parameter< double >::type colmax(colmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_knn_impute_mem(Bin, k, maxp, rowmax, colmax));
    return rcpp_result_gen;
END_RCPP
}
// mc_knn_impute_hdf5
Rcpp::NumericMatrix mc_knn_impute_hdf5(std::string filename, std::string group, std::string dataset, int k, int maxp, double rowmax, double colmax);
RcppExport SEXP _methylclock_mc_knn_impute_hdf5(SEXP filenameSEXP, SEXP groupSEXP, SEXP datasetSEXP, SEXP kSEXP, SEXP maxpSEXP, SEXP rowmaxSEXP, SEXP colmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type group(groupSEXP);
    Rcpp::traits::input_parameter< std::string >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type maxp(maxpSEXP);
    Rcpp::traits::input_parameter< double >::type rowmax(rowmaxSEXP);
    Rcpp::traits::input_parameter< double >::type colmax(colmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_knn_impute_hdf5(filename, group, dataset, k, maxp, rowmax, colmax));
    return rcpp_result_gen;
END_RCPP
}
// mc_omp_set_threads
int mc_omp_set_threads(int n);
RcppExport SEXP _methylclock_mc_omp_set_threads(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_omp_set_threads(n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_methylclock_altumage_forward", (DL_FUNC) &_methylclock_altumage_forward, 2},
    {"_methylclock_bnn_predict", (DL_FUNC) &_methylclock_bnn_predict, 1},
    {"_methylclock_mc_knn_impute_mem", (DL_FUNC) &_methylclock_mc_knn_impute_mem, 5},
    {"_methylclock_mc_knn_impute_hdf5", (DL_FUNC) &_methylclock_mc_knn_impute_hdf5, 7},
    {"_methylclock_mc_omp_set_threads", (DL_FUNC) &_methylclock_mc_omp_set_threads, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_methylclock(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
