# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' AltumAge forward pass (C++/Eigen, weights from HDF5)
#'
#' @param weights_file HDF5 file with the scaler and layer weights.
#' @param Xin Beta matrix aligned to the reference CpGs (features x samples).
#' @return A numeric vector, one predicted age per sample.
#' @keywords internal
#' @export
altumage_forward <- function(weights_file, Xin) {
    .Call(`_methylclock_altumage_forward`, weights_file, Xin)
}

bnn_predict <- function(odata) {
    .Call(`_methylclock_bnn_predict`, odata)
}

#' KNN-impute a matrix in memory (C++/Eigen, block split via BigDataStatMeth)
#'
#' Fills the missing entries of a CpGs x samples matrix from each CpG's k
#' nearest co-varying CpGs. A row set within \code{maxp} is imputed exactly
#' (every CpG can be a neighbour of every other); a larger one is first split
#' into blocks of similar CpGs through a BigDataStatMeth SVD embedding and
#' 2-means, then each block is imputed exactly.
#'
#' @param Bin Numeric matrix (CpGs x samples); missing values are \code{NA}.
#' @param k Number of neighbours averaged for each imputed value.
#' @param maxp Largest block imputed exactly; larger row sets are split first.
#' @param rowmax A row with a greater missing fraction than this is filled with
#'   the per-column mean instead of by KNN.
#' @param colmax A column with a greater missing fraction than this is flagged
#'   (a warning is raised in R); imputation still proceeds.
#' @return The matrix with missing values filled.
#' @keywords internal
mc_knn_impute_mem <- function(Bin, k = 10L, maxp = 1500L, rowmax = 0.5, colmax = 0.8) {
    .Call(`_methylclock_mc_knn_impute_mem`, Bin, k, maxp, rowmax, colmax)
}

#' KNN-impute a matrix stored in HDF5 (reads through BigDataStatMeth)
#'
#' Reads a CpGs x samples matrix from an HDF5 dataset in R-view order through
#' the BigDataStatMeth C++ API (so the R/HDF5 layout is reconciled by the
#' library), imputes it with the same engine as \code{mc_knn_impute_mem}, and
#' returns the filled matrix. This validates the HDF5 read path against the
#' in-memory one; the memory-bounded block-wise variant builds on it.
#'
#' @param filename HDF5 file path.
#' @param group Group holding the dataset.
#' @param dataset Dataset name (CpGs x samples in R view).
#' @param k,maxp,rowmax,colmax See \code{mc_knn_impute_mem}.
#' @return The filled matrix (CpGs x samples), without dimnames.
#' @keywords internal
mc_knn_impute_hdf5 <- function(filename, group, dataset, k = 10L, maxp = 1500L, rowmax = 0.5, colmax = 0.8) {
    .Call(`_methylclock_mc_knn_impute_hdf5`, filename, group, dataset, k, maxp, rowmax, colmax)
}

.mc_omp_set_threads <- function(n) {
    .Call(`_methylclock_mc_omp_set_threads`, n)
}

